# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from change_stu import *
from change_course import *
from change_score import *
class Modify(QtWidgets.QMainWindow):
    def __init__(self):
        super(Modify,self).__init__()
        self.centralwidget = None
        self.commandLinkButton = None
        self.commandLinkButton_2 = None
        self.commandLinkButton_3 = None
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(280, 180, 222, 48))
        self.commandLinkButton.setObjectName("commandLinkButton")

        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(280, 280, 222, 48))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")

        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(280, 380, 222, 48))
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.commandLinkButton.clicked.connect(self.change_stu)
        self.commandLinkButton_2.clicked.connect(self.change_course)
        self.commandLinkButton_3.clicked.connect(self.change_score)




    def change_stu(self):
        self.ui_1=Modify_stu()
        self.ui_1.show()


    def change_course(self):
        self.ui_2=Modify_course()
        self.ui_2.show()

    def change_score(self):
        self.ui_2 = Modify_score()
        self.ui_2.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.commandLinkButton.setText(_translate("MainWindow", "修改学生信息"))
        self.commandLinkButton_2.setText(_translate("MainWindow", "修改课程信息"))
        self.commandLinkButton_3.setText(_translate("MainWindow", "修改成绩信息"))
