# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import pymysql
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Modify_stu(QtWidgets.QMainWindow):
    def __init__(self):
        super(Modify_stu, self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 480, 90, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 480, 90, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(230, 50, 340, 430))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.verticalLayout.addWidget(self.line)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)

        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)

        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)

        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)

        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)

        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)

        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)

        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)

        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)

        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)

        self.line_5 = QtWidgets.QFrame(self.widget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)

        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout.addWidget(self.lineEdit_5)

        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)

        # self.line_6 = QtWidgets.QFrame(self.widget)
        # self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        # self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        # self.line_6.setObjectName("line_6")
        # self.verticalLayout.addWidget(self.line_6)


        # self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        # self.lineEdit_6.setObjectName("lineEdit_6")
        # self.verticalLayout.addWidget(self.lineEdit_6)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.insert)
        self.pushButton_2.clicked.connect(self.delete)

    def insert(self):
        num, name, de_name, classid, dorm = self.lineEdit.text(), self.lineEdit_2.text(), self.lineEdit_3.text(), \
                                            self.lineEdit_4.text(), self.lineEdit_5.text()
        if not num or not name or not de_name or not classid or not dorm: # 插入错误值，空值，提醒
            QMessageBox.warning(self, '警告', '请输入学号、姓名与班号')
        elif len(num) != 4:
            QMessageBox.warning(self, '警告', '学号为4位数字')
        else:
            con = pymysql.connect(host='localhost', port=3306, user='root', password='fkl001206', charset='utf8',
                                  database='lab1')  # 连接数据库
            cur = con.cursor()  # 执行sql语句的游标
            query = 'select * from student where sid=%s'
            if cur.execute(query, [num]):
                QMessageBox.warning(self, '插入异常', '该学号已存在，请重新输入') # 重复值提示
            elif not cur.execute('select * from department where name = %s', [de_name]):
                QMessageBox.warning(self, '插入异常', '该专业不存在，请尝试插入正确条目')
            else:
                QMessageBox.information(self, '成功', '成功插入一条学生数据')
                query = 'insert into student(sid, sname, de_name, class, dorm) values (%s, %s, %s, %s, %s)'
                cur.execute(query, [num, name, de_name, classid, dorm])
                con.commit()


    def delete(self):
        num= self.lineEdit.text()
        if not num:
            QMessageBox.warning(self, '警告', '学号为空')
        elif not num.isdigit() or len(num) != 4:
            QMessageBox.warning(self, '警告', '学号只可为4位数字')
        else:
            con = pymysql.connect(host='localhost', port=3306, user='root', password='fkl001206', charset='utf8',
                                  database='lab1')  # 连接数据库
            cur = con.cursor()  # 执行sql语句的游标
            query = 'select * from student where sid=%s'
            if not cur.execute(query, [num]):
                QMessageBox.warning(self, "删除异常", "该学号不存在，请重新输入")
            else:
                if cur.execute('select * from grade where sid=%s', [num]):
                    QMessageBox.information(self, '提示', '该学号在其他表中被作为外键引用，触发器已默认删除其他表中对应条目的数据')
                    query = 'delete from grade where sid=%s'
                    cur.execute(query, [num])
                QMessageBox.information(self, '成功', '成功删除学生数据')
                query = 'delete from student where sid=%s'
                cur.execute(query, [num])
                con.commit()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "插入"))
        self.pushButton_2.setText(_translate("MainWindow", "删除"))
        self.label.setText(_translate("MainWindow", "学号"))
        self.label_2.setText(_translate("MainWindow", "姓名"))
        self.label_3.setText(_translate("MainWindow", "所在系"))
        self.label_4.setText(_translate("MainWindow", "班号"))
        self.label_5.setText(_translate("MainWindow", "宿舍号"))
