# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import random

import pymysql
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QTableWidgetItem
from table import *

class Index(QtWidgets.QMainWindow):

    def __init__(self):
        super(Index, self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 624)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(100, 60, 391, 221))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")

        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(100, 60, 72, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(200, 120, 93, 28))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(150, 60, 161, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")

        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(100, 320, 391, 221))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")

        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(100, 60, 81, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 120, 93, 28))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(150, 50, 161, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(9)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.create_department_view)
        self.pushButton_2.clicked.connect(self.index)

        tab1 = []
        con = pymysql.connect(host='localhost', port=3306, user='root', password='fkl001206', charset='utf8',
                              database='lab1')  # 连接数据库
        cur = con.cursor()
        sql = "SELECT * FROM student"
        cur.execute(sql)
        for item in cur.fetchall():
            if item[2] not in tab1:
                tab1.append(item[2])
        self.comboBox.addItems(tab1)
        self.comboBox_2.addItems(['姓名', '院系', '班级', '寝室'])
        cur.close()
        con.close()

    def create_department_view(self):
        d_name = self.comboBox.currentText()
        view_name = '学生_' + d_name
        con = pymysql.connect(host='localhost', port=3306, user='root', password='fkl001206', charset='utf8',
                              database='lab1')  # 连接数据库
        cur = con.cursor()
        query = 'select count(*) from information_schema.VIEWS where TABLE_SCHEMA="lab1" and TABLE_NAME=%s'
        cur.execute(query, [view_name])  # 先查询视图是否已被定义
        if cur.fetchone()[0] == 1:
            QMessageBox.warning(self, '警告', '视图已被定义：' + view_name)
        else:
            query = 'create view ' + view_name + ' as select sid ,sname, class, dorm from student where de_name = %s'
            cur.execute(query, [d_name])
            QMessageBox.information(self, '成功', '成功创建视图：' + view_name)
            cur.close()
            con.close()


    def index(self):
        dic = {'0': 'sname', '1': 'de_name', '2': 'class', '3': 'dorm'}
        con = pymysql.connect(host='localhost', port=3306, user='root', password='fkl001206', charset='utf8',
                              database='lab1')  # 连接数据库
        cur = con.cursor()
        # index = self.comboBox_2.currentText().split()[0]
        # print(index)
        index = dic[str(self.comboBox_2.currentIndex())]
        # print(index1)

        query = 'select count(*) from information_schema.INNODB_INDEXES where NAME=%s'
        cur.execute(query, [index + '_index'])  # 先查询视图是否已被定义
        if cur.fetchone()[0] == 1:
            QMessageBox.warning(self, '警告', '索引已被定义：' + index)
        else:
            query = 'create index ' + index + '_index on student(' + index + ' ) '
            cur.execute(query)
            QMessageBox.information(self, '成功', '成功创建索引：' + index + '_index')
        cur.close()
        con.close()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "为某院系建立视图"))
        self.label.setText(_translate("MainWindow", "院系"))
        self.pushButton.setText(_translate("MainWindow", "建立"))
        self.groupBox_2.setTitle(_translate("MainWindow", "为学生非键属性建立索引"))
        self.label_2.setText(_translate("MainWindow", "属性"))
        self.pushButton_2.setText(_translate("MainWindow", "建立"))
